function downloadText(name, text, type='application/json') { const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
async function exportBackup() { const data={version:2,exportedAt:new Date().toISOString(),students:await DB.all('students'),history:await DB.all('history'),settings:await DB.all('settings'),absences:await DB.all('absences'),meta:await DB.all('meta'),exams:await DB.all('exams'),examResults:await DB.all('examResults')}; downloadText(`课堂点名备份-${localDate()}.json`,JSON.stringify(data,null,2)); }
async function exportHistory() { const [history,students]=await Promise.all([DB.all('history'),DB.all('students')]); const map=new Map(students.map(s=>[s.id,s])); const rows=[['时间','班级','学号','姓名','难度']]; history.forEach(x=>{const s=map.get(x.studentId)||{}; rows.push([new Date(x.at).toLocaleString(),s.className||'',s.id||x.studentId,s.name||'',x.difficulty||'']);}); downloadText(`点名历史-${localDate()}.csv`,rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv;charset=utf-8'); }

function xmlEscape(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
async function downloadGradeTemplate(){
  if(typeof JSZip==='undefined'){toast('模板组件尚未加载，请刷新页面重试');return;}
  const zip=new JSZip();
  zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');
  zip.file('_rels/.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
  zip.file('xl/workbook.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="成绩数据" sheetId="1" r:id="rId1"/></sheets></workbook>');
  zip.file('xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');
  const headers=['班级','学号','姓名','最终总评成绩','班级排名','段排名'];
  const cells=headers.map((value,index)=>{const col=String.fromCharCode(65+index);return `<c r="${col}1" t="inlineStr"><is><t>${xmlEscape(value)}</t></is></c>`;}).join('');
  zip.file('xl/worksheets/sheet1.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1">${cells}</row><row r="2"></row></sheetData></worksheet>`);
  const blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='成绩导入模板.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}
